### PR TITLE
Win32

### PR DESCRIPTION
**Pull request by gwenn**
As promised!
More coming...

### CODE REVIEW

**Comment by gwenn** [comment]
Tested (not thoroughly) at work with cmd and powershell.
Fix #37

**Comment by kkawakam** [comment]
I am good with all the changes you made. I would definitely would like to move the platform specific logic for clear_screen() and refresh() to the tty module (maybe not the best name for it?) but it doesn't have to be part of this PR.

**Comment by gwenn** [comment]
I tried to move `clear_screen` but there is a visibility problem:
```
src/tty/unix.rs:106:29: 106:34 error: private type in public interface [E0446]
src/tty/unix.rs:106 pub fn clear_screen(s: &mut State) -> Result<()> {
```

**Comment by kkawakam** [comment]
@gwenn, yea it isn't really important right now.  I'm sure something needs to be refactored to get that working.

**Comment by kkawakam** [comment]
@gwenn Do you have more changes coming in?

**Comment by gwenn** [comment]
I think so:
* Powershell & ctrl-L:
thread 'main' panicked at 'attempted to multiply with overflow', src\lib.rs:255
* Powershell ISE:
Error: Io(Error { repr: Os { code: 6, message: "The handle is invalid." } })

**Comment by kkawakam** [comment]
@gwenn Out of the new issues you created, you're addressing  #63, #56, #55 specifically in this branch?  Just let me know when you're good to go, so I can take a final look + merge.

**Comment by gwenn** [comment]
Definitely not #56.
Probably not #63.
Surely #55.

**Comment by gwenn** [comment]
* For #63, could you please check if you receive WINDOW_BUFFER_SIZE_EVENT when resizing the console (with Cmd or Powershell) ? Just add a debug statement [here](https://github.com/gwenn/rustyline/blob/win32/src/tty/windows.rs#L135)
```
writeln!(io::stderr(), "rec: {:?}", rec).unwrap();
```
Normally, setting the ENABLE_WINDOW_INPUT [here](https://github.com/gwenn/rustyline/blob/win32/src/tty/windows.rs#L88)

 * For #56, it may be related to this one: https://github.com/retep998/wio-rs/issues/5. If linenoise-ng example works in Powershell ISE, there is a bug in rustyline.

**Comment by kkawakam** [comment]
@gwenn for #63 Confirmed WINDOW_BUFFER_SIZE_EVENT when resizing the console in Cmd & Powershell

**Comment by kkawakam** [comment]
So I was taking a look at #56 and it seems like interactive console applications aren't really supported in  Powershell ISE.
 * https://blogs.msdn.microsoft.com/powershell/2009/02/04/console-application-non-support-in-the-ise/

* https://blogs.msdn.microsoft.com/powershell/2009/04/17/differences-between-the-ise-and-powershell-console/

I also found this piece of code [link](https://github.com/neurocline/catalog/blob/master/cpp/src/WinConsoleHelpers.cpp#L32) that says:
```
// Grr, Powershell ISE says FILE_TYPE_PIPE all the time, evidently it runs as a pipe
// to the console? This might be an artifact of 2.0, evidently in 3.0 the output and
// command panes are merged.
```
This might be the reason why GetConsoleScreenBufferInfo is failing because stdout is a FILE_TYPE_PIPE and not a FILE_TYPE_CHAR.

**Pull request merged**
