### PR TITLE
Implement Candidate for str

### LINKED ISSUE #443: Implement Candidate for &str
This might be a nice addition

```rust
impl Candidate for &str {
    fn display(&self) -> &str {
        self
    }

    fn replacement(&self) -> &str {
        self
    }
}

```

### PR DESCRIPTION
**Pull request by gwenn**
Should fix #443

### CODE REVIEW

**Comment by LoganDark** [comment]
How exactly am I expected to provide a vector of `str`? They're literally DSTs.

**Comment by gwenn** [comment]
> How exactly am I expected to provide a vector of `str`? They're literally DSTs.

Please provide a minimal example that should but doesn't work.

**Comment by LoganDark** [comment]
> > How exactly am I expected to provide a vector of `str`? They're literally DSTs.
> 
> Please provide a minimal example that should but doesn't work.

```rust
impl Completer for LineHelper {
	type Candidate = &'static str;

	fn complete(
		&self,
		_line: &str,
		_pos: usize,
		_ctx: &rustyline::Context<'_>,
	) -> rustyline::Result<(usize, Vec<Self::Candidate>)> {
		Ok((0, vec!["test1", "test2"]))
	}
}
```

**Comment by gwenn** [comment]
> > > How exactly am I expected to provide a vector of `str`? They're literally DSTs.
> > 
> > 
> > Please provide a minimal example that should but doesn't work.
> 
> ```rust
> impl Completer for LineHelper {
> 	type Candidate = &'static str;
> 
> 	fn complete(
> 		&self,
> 		_line: &str,
> 		_pos: usize,
> 		_ctx: &rustyline::Context<'_>,
> 	) -> rustyline::Result<(usize, Vec<Self::Candidate>)> {
> 		Ok((0, vec!["test1", "test2"]))
> 	}
> }
> ```

`Candidate` should be `str`: `type Candidate = str;`

**Comment by LoganDark** [comment]
> > > > How exactly am I expected to provide a vector of `str`? They're literally DSTs.
> > > 
> > > 
> > > Please provide a minimal example that should but doesn't work.
> > 
> > 
> > ```rust
> > impl Completer for LineHelper {
> > 	type Candidate = &'static str;
> > 
> > 	fn complete(
> > 		&self,
> > 		_line: &str,
> > 		_pos: usize,
> > 		_ctx: &rustyline::Context<'_>,
> > 	) -> rustyline::Result<(usize, Vec<Self::Candidate>)> {
> > 		Ok((0, vec!["test1", "test2"]))
> > 	}
> > }
> > ```
> 
> `Candidate` should be `str`: `type Candidate = str;`

Exactly, and then I can't return a vec because `str` is a DST. Try it yourself.

**Comment by gwenn** [comment]
> > > > > How exactly am I expected to provide a vector of `str`? They're literally DSTs.
> > > > 
> > > > 
> > > > Please provide a minimal example that should but doesn't work.
> > > 
> > > 
> > > ```rust
> > > impl Completer for LineHelper {
> > > 	type Candidate = &'static str;
> > > 
> > > 	fn complete(
> > > 		&self,
> > > 		_line: &str,
> > > 		_pos: usize,
> > > 		_ctx: &rustyline::Context<'_>,
> > > 	) -> rustyline::Result<(usize, Vec<Self::Candidate>)> {
> > > 		Ok((0, vec!["test1", "test2"]))
> > > 	}
> > > }
> > > ```
> > 
> > 
> > `Candidate` should be `str`: `type Candidate = str;`
> 
> Exactly, and then I can't return a `Vec<Self::Candidate>` because `str` is a DST. Try it yourself.
> 
> The issue is that `str` is unusable as a candidate because it is not `Sized`. But I can't use `&str` as the candidate because you only implement `Candidate` for `str` itself.

You are right.
And I don't remember why I provided an impl for `str` and not:
```rust
impl Candidate for &'static str {
    fn display(&self) -> &str {
        self
    }

    fn replacement(&self) -> &str {
        self
    }
}
```

**Comment by LoganDark** [comment]
> You are right.
> And I don't remember why I provided an impl for `str` and not:
> 
> ```rust
> impl Candidate for &'static str {
>     fn display(&self) -> &str {
>         self
>     }
> 
>     fn replacement(&self) -> &str {
>         self
>     }
> }
> ```

I believe it was because you raised concerns about only supporting `'static` and not other lifetimes. But changing that would mean rustyline v9.0.0, so...

**Comment by gwenn** [comment]
> I believe it was because you (or someone) raised concerns about only supporting `'static` and not other lifetimes. But changing that would mean rustyline v9.0.0, so...

No, we can still patch v8 and provide an impl for `&'static str` (and keep the old / unusable one).
See #512

**Comment by LoganDark** [comment]
> > I believe it was because you (or someone) raised concerns about only supporting `'static` and not other lifetimes. But changing that would mean rustyline v9.0.0, so...
> 
> No, we can still patch v8 and provide an impl for `&'static str` (and keep the old / unusable one).
> See #512

I meant supporting other lifetimes would mean v9, so yeah, supporting static can be done here.

**Pull request merged**
