### PR TITLE
Add derive feature that reexports rustyline-derive's API

### PR DESCRIPTION
**Pull request by figsoda**

### CODE REVIEW

**Comment by gwenn** [comment]
Check:
- [ ] (cargo doc)[https://github.com/kkawakam/rustyline/blob/master/Cargo.toml#L88]
- [ ] (doc.rs)[https://github.com/kkawakam/rustyline/blob/master/Cargo.toml#L88] features
- [ ] (test/example)[https://github.com/kkawakam/rustyline/blob/master/Cargo.toml#L60]

**Comment by figsoda** [comment]
> cargo doc

not sure what documentation to add since there wasn't any for rustyline-derive, but it does show up in the `Derive macros` section on docs.rs

image

**Comment by gwenn** [comment]
> > cargo doc
> 
> not sure what documentation to add since there wasn't any for rustyline-derive, but it does show up in the `Derive macros` section on docs.rs 

I am not sure if it is possible but ideally they should be marked as available only with `derive` feature like [here](https://docs.rs/rustyline/latest/rustyline/struct.EventContext.html).

**Comment by figsoda** [comment]
that seems to be possible, I have added that

**Comment by gwenn** [comment]
Thanks !

**Pull request merged**
