### PR TITLE
Vi: insert mode escape seq fallback to command mode

### PR DESCRIPTION
**Pull request by homburg**
Inspired by #416 

In vi insert mode:

If getting an unrecognized escape sequence, assume it is a command input instead. eg `Esc, j`

### CODE REVIEW

**Comment by homburg** [comment]
@gwenn I have updated this to call the new function `vi_command_with_key` to get the correct fast command mode switch behavior. Do you have any comments?

**Comment by gwenn** [comment]
https://github.com/homburg/rustyline/pull/1 !

**Comment by homburg** [comment]
@gwenn Great! Missed your pr (obviously). It works perfectly

**Comment by gwenn** [comment]
Thanks.

**Pull request merged**
