### PR TITLE
feat: adding CircularList completion behavior

### PR DESCRIPTION
**Pull request by ahkrr**
This PR is adding CircularList behavior in the complete_line function.
The list will stay and update in place. 
Resizing the terminal can cause the displayed list to appear problematically, which can be resolved by another TAB, which will clear the terminal from the cursor-position until the end and redraw the list.
I wrote this because nushell is using rustyline and I wanted this feature for it.
I currently use oh-my-zsh.
This PR is also related to this #302
The gif below is nushell using the additions to rustyline.
t-rec

### CODE REVIEW

**Comment by gwenn** [comment]
Thanks.
I would prefer that `Completer` trait is enhanced and let users implement their own `show_candidates` method.
Which means that we need an API to move cursor and write on screen.

**Comment by ahkrr** [comment]
I only know as much about writing to a terminal as was needed for this PR.
In the rust ecosystem, is it really necessary to build another `API` to interact with terminals. 
Couldn't the `Completer` be extended without building the terminal `API` and having the users use things like [crossterm](https://lib.rs/crates/crossterm) or [console](https://lib.rs/crates/console).
Instead of building an API in rustyline, one could build examples, that work with [crossterm](https://lib.rs/crates/crossterm) or [console](https://lib.rs/crates/console) to show of some functionality.
Is this PR not of interest because of plans for rustyline or could it be integrated under certain circumstances?
Extensibility is a nice thing but having some choice in defaults is also nice.

**Comment by gwenn** [comment]
Currently the [Renderer](https://github.com/kkawakam/rustyline/blob/master/src/tty/mod.rs#L30) trait is not public so only `rustyline` can write on terminal screen.
And I guess that `crossterm` and `console` expect exclusive access to terminal screen.
So using `crossterm` for completions means implementing [Term](https://github.com/kkawakam/rustyline/blob/master/src/tty/mod.rs#L201) with `crossterm`...

See how `linefeed` allows users to [write](https://docs.rs/linefeed/0.6.0/linefeed/prompter/struct.Prompter.html#method.writer_append) on screen (but not from [Completer](https://docs.rs/linefeed/0.6.0/linefeed/complete/trait.Completer.html) because of immutable ref).

**Comment by ahkrr** [comment]
The `terminal` in `windows` or `unixes` isn't limited by ownership, is it? 
If someone were to use `crosserterm` etc. to manipulate the `terminal`, as long as they restore the position to what `rustyline` expects, `rustyline` should be able to draw itself without problems, should it not? If a terminal API would be included in `rustyline`, wouldn't it use the same ways to manipulate the terminal as `crossterm` etc. ?

**Comment by gwenn** [comment]
Only if `crossterm` does not keep a [lock](https://doc.rust-lang.org/std/io/struct.StdoutLock.html) on stdout.

**Pull request closed without merging**
