### PR TITLE
Draft for #82

### PR DESCRIPTION
**Pull request by gwenn**

### CODE REVIEW

**Comment by Yamakaky** [comment]
Why not just `impl Iterator for Rustyline`?

**Comment by gwenn** [comment]
Because there is no default prompt.
Do you have any idea how to specify the prompt ?

**Comment by Yamakaky** [comment]
Maybe just allow for a default prompt to be set?

**Comment by kkawakam** [comment]
@Yamakaky @gwenn is this a satisfactory solution for this?  I am neutral on whether we specify a default prompt or not.

**Comment by Yamakaky** [comment]
I'm not sure, either should be fine.

**Pull request merged**
