### PR TITLE
Replace use of unstable features

### PR DESCRIPTION
**Pull request by birkenfeld**
Tested to work with stable rustc 1.9.0.

### CODE REVIEW

**Comment by kkawakam** [comment]
@birkenfeld can you update the .travis.yml to use stable rust (or maybe pinned to a specific version)?

**Comment by kkawakam** [comment]
@gwenn are you doing any changes on your fork right now where going to stable will cause you some issues?

**Comment by birkenfeld** [comment]
@kkawakam sure!

**Comment by gwenn** [comment]
@kkawakam no, I will keep on using the unstable version.

**Comment by kkawakam** [comment]
@birkenfeld I'll push a new version to crates.io soon.

**Pull request merged**
