### PR TITLE
External print

### PR DESCRIPTION
**Pull request by gwenn**
See #229

```sh
cargo run --example external_print
```

To do:
* ~~Windows platform (only one printer supported, and when the printer is dropped we still wait)~~
* Check interaction with history search, completion, ...

### CODE REVIEW

**Comment by gwenn** [comment]
https://github.com/ghc/ghc/blob/master/libraries/base/cbits/inputReady.c#L325
> nightmare.  A Console Handle will appear to be ready
> ...

**Comment by gwenn** [comment]
Something is broken with last merge.
Sorry.

**Comment by tailhook** [comment]
It works fine, except for the following issue:

If I don't put a newline to the output or the external printer like `printer.write(" ")`, rustyline hangs.

While I understand that partial line would interfere with input prompt, it's better to have clobbered prompt (which will eventually fix on next keystrokes), than hanging.

**Comment by flxo** [comment]
Hi.

I tried this branch and discovered the following: When using the printer from different threads, the blocking `readline` call somehow interferes with the `std::io::Write` implementation produced by `create_external_printer`. 

Here's a (hacky) minimal example with two thread sending/listening on channels. One thread performs the `readline` and the other one just prints.

```rust
use std::{io::Write, sync::mpsc, thread};
use rustyline::Editor;

fn main() {
    let mut rl = Editor::<()>::new();

    let mut printer = rl.create_external_printer().unwrap();
    let print = {
        let (tx, rx) = mpsc::channel::<String>();
        thread::spawn(move || {
            while let Ok(line) = rx.recv() {
                printer.write_all(line.as_bytes()).expect("Failed to write");
                printer.write_all(b"\n").expect("Failed to write");
                printer.flush().expect("Failed to flush");
            }
        });
        tx
    };

    let readline = {
        let (tx, rx) = mpsc::channel::<String>();
        thread::spawn(move || {
            loop {
                match rl.readline(">> ") {
                    Ok(line) => {
                        rl.add_history_entry(line.as_str());
                        tx.send(line).ok();
                        //std::thread::sleep(std::time::Duration::from_secs(2));
                    },
                    _ => break,
                }
            }
        });
        rx
    };

    loop {
        match readline.recv() {
            Ok(line) => {
                for n in 0..10 {
                    print.send(format!("{} {}", n, line)).ok();
                }
            }
            Err(_)=> break,
        }
    }
}
```

With `rustyline = { git = "https://github.com/gwenn/rustyline.git", branch = "external-print", features = ["with-fuzzy"] }`

The output is e.g:

```
>> AAA
0 AAA
>> BBB
1 AAA
2 AAA
3 AAA
4 AAA
5 AAA
6 AAA
7 AAA
8 AAA
9 AAA
0 BBB
>> CCC
1 BBB
2 BBB
3 BBB
4 BBB
5 BBB
6 BBB
7 BBB
8 BBB
9 BBB
0 CCC
>>
```

The 9 `AAA`s are printed after `BBB` is entered and return is hit. Looks like some buffer within the printer is not flushed correctly or the writing is blocked.

Originally I'm using `rustyline` in a Tokio environment and run the `readline` and the printing in `spawn_blocking` Tokio tasks. The behaviour is the same as with the std threads. 

For testing, I added a stupid `sleep` for 5 secons in the readline thread after each input and the output is printed as expected.

**Comment by gwenn** [comment]
> I tried this branch and discovered the following: When using the printer from different threads, the blocking `readline` call somehow interferes with the `std::io::Write` implementation produced by `create_external_printer`.

On unix or windows ?

**Comment by flxo** [comment]
> > I tried this branch and discovered the following: When using the printer from different threads, the blocking `readline` call somehow interferes with the `std::io::Write` implementation produced by `create_external_printer`.
> 
> On unix or windows ?

Sorry forgot to add this. I tested on a x86 Linux and Mac.

**Comment by gwenn** [comment]
I will try to have a look this week-end.

**Comment by gwenn** [comment]
@flxo Ok, we should not use a `BufReader` [here](https://github.com/kkawakam/rustyline/pull/235/files#diff-bc8fd5ba686c57cce3f8eefc70d2b5419468e9c84b5d1923095584f8dabb010bR1222). Because buffered lines are not "selectable" anymore...

**Comment by gwenn** [comment]
@flxo Your issue should have been fixed by 0a5f0a4 on unix platform.

**Comment by flxo** [comment]
@gwenn Thanks for the update. I tried your patches and the issue is gone. 

In my software I have a (hacky) `std::io::Write` impl around the `rustyline::ExternalPrinter` which allows me to use `std::io::stdout` and the rustyline interface dependant on the use case (iteractive or not).
Would it be possible to provide `std::io::Write` directly?

**Comment by gwenn** [comment]
> @gwenn Thanks for the update. I tried your patches and the issue is gone.
> 
> In my software I have a (hacky) `std::io::Write` impl around the `rustyline::ExternalPrinter` which allows me to use `std::io::stdout` and the rustyline interface dependant on the use case (iteractive or not).
> Would it be possible to provide `std::io::Write` directly?

You should be able to implement an `ExternalPrinter` that writes to `stdout`, no ?

**Comment by flxo** [comment]
@gwenn My idea is to do something like

```rust
impl<T> std::io::Write for T where T: ExternalPrinter {
   ...
}
```

The prints are some via the `writeln!` family and with the `impl` of `std::io::Write` I can decided whether to use `std::io::Stdout` for non interactive usage (there's no rustyline::Editor around) and the thing returned from `create_external_printer`

```rust
let out = if interactive {
  Box::new(rl.create_external_printer()?) as Box<dyn std::io::Write>
} else {
  Box::new(std::io::stdout()) as Box<dyn std::io::Write>
}

writeln!(out, "test");
```

**Comment by gwenn** [comment]
The `ExternalPrinter` is now message oriented (`\n` is not meaningful anymore).
And `Write` is bytes/stream oriented.
So I would prefer that you implements `Write` on your own ExternalPrinter wrapper.

**Comment by bartlomieju** [comment]
Is there any chance this PR could be landed? We use `rustyline` for REPL in Deno and this feature would greatly improve the experience for streaming output (https://github.com/denoland/deno/issues/8049), currently the output is interleaved with prompt line.

**Comment by gwenn** [comment]
> Is there any chance this PR could be landed?

Current implementation is incomplete on windows.
> EDIT: Actually not a huge priority, we're gonna experiment with different crate for this purpose https://docs.rs/reedline

#579

**Comment by vi** [comment]
> Current implementation is incomplete on windows.

Can UNIX-only implementation land first then?

**Comment by gwenn** [comment]
Could you please give it another try (windows implementation should be fine now) ?
Thanks.

**Pull request merged**
