### PR TITLE
Implement refreshSingleLine & linenoiseEditInsert.

### PR DESCRIPTION
**Pull request by gwenn**
And attempt to support unicode input.

### CODE REVIEW

**Comment by kkawakam** [comment]
@gwenn , I am taking a look at these changes now.  Sorry about the delay.

**Comment by gwenn** [comment]
I will try to add incremental history search and fix completion in my next pull request...

**Comment by kkawakam** [comment]
@gwenn, would you happen to know when the unstable features below are going to be stabilized?  
```rust
#![feature(drain)]
#![feature(io)]
#![feature(str_char)]
#![feature(unicode)]
```
My original intent was to be able to support Rust stable but at this point in time I know it would be annoying to work around the unstable features..

**Comment by gwenn** [comment]
Sorry, I don't know.

**Pull request merged**
