### PR TITLE
Page completions

### PR DESCRIPTION
**Pull request by gwenn**
BREAKING CHANGE

### CODE REVIEW

**Comment by gwenn** [comment]
Fix #57

**Comment by kkawakam** [comment]
@gwenn sorry for the late response.  Can we limit the scope of the breaking API changes and just ```#[deprecated]``` the functions?  We can remove the deprecated functionality when we go 2.0.0 but I don't want it to prevent us from pushing minor version changes in the meanwhile.

**Comment by gwenn** [comment]
Sorry but I don't really care.
Maybe we can go back to something like version 0.3 ?
Or leave this pull request unmerged until version 2.0 ?

**Comment by kkawakam** [comment]
@gwenn can you rebase against master (or merge) ? I'm going to merge this in once that it is done. I think it's better to merge this in rather than waiting.  Thanks!

**Comment by gwenn** [comment]
Done.

**Pull request merged**
