### PR TITLE
Try to fix nightly build

### PR DESCRIPTION
**Pull request by gwenn**
See #217

### CODE REVIEW

**Comment by gwenn** [comment]
We need help to make the fix works on stable and nightly.

**Comment by nevi-me** [comment]
What's the earliest nightly that this breaks on? I'm trying to reproduce on Windows as it's breaking our builds

**Comment by lopopolo** [comment]
@nevi-me somewhere between `nightly-2019-05-07` and `nightly-2019-05-16`

**Comment by nevi-me** [comment]
I might have a fix, will submit a PR shortly. It's not 'nice' though

**Comment by nevi-me** [comment]
I've submitted #219

**Pull request merged**
